common :
  nb_of_days : 180 #include non-trading day
  max_missing_data : .02
  fetching : True
  preprocessing : True
  model_phase : 'predict'

position_management :
  trading_capital : 37000
  risk_per_trade : 0.01
  return_in_quantile : 0.01
  quantile : 90

inputs:
  past_covariates :
    - source: 'yahoo'
      data:
        - "DOLE"
#        - 'GC=F'
#        - 'YM=F'
#        - 'SPY'
#        - 'ZW=F'
#        - 'SI=F'
#        - 'set_dynamically_50_largest_stocks'
#        - 'NATURAL_GAS'
#        - '3month'
#        - '10year'
#        - '2year'
#        - 'EUR'
#        - 'WTI'
#        - 'MSFT'
#        - 'GOOGL'
#        - 'AAPL'
#        - 'AMZN'
#    - source : 'fred'
#      data:
#        - 'set_dynamically'
#        - 'T5YIE'
#        - 'T10YIE'
#        - 'DEXUSNZ'
#        - 'VIXCLS'
#    - source : 'macrotrends'
#      data :
#         - 'set_dynamically'
#         - 'wheat'
#         - 'corn'
